### ISSUE TITLE
Can the AppImage be downloaded somewhere?

### ISSUE THREAD

**Issue by probonopd** [zrythm/zrythm-installer#1]
https://github.com/zrythm/zrythm-installer/blob/10f52224340e39e13f8bb9cd7fde23edd13d4a13/tasks/ubuntu_deploy.yml#L9

Can the AppImage be downloaded somewhere? We would like to add it to https://appimage.github.io/.

**Comment by alex-tee** [comment]
@probonopd it doesn't work properly at the moment so it's not available anywhere

it's a little messy but this snippet used to build at some point - you can probably get it to work with some modifications:
https://github.com/zrythm/zrythm-installer/blob/master/Makefile#L456

**Comment by probonopd** [comment]
Thanks @alex-tee. What is not working? For `linuxdeploy` related issues please post an example (including errors you are getting) over at https://github.com/linuxdeploy/linuxdeploy/issues, thanks.

**Comment by alex-tee** [comment]
@probonopd I don't remember, sorry, it's been a while since I tried this and it's disabled now

> For linuxdeploy related issues please post an example (including errors you are getting) over at https://github.com/linuxdeploy/linuxdeploy/issues

thanks, I'll try to get it building again soon and report if there's any issues

**Comment by alex-tee** [comment]
@probonopd https://sendowl-bucket.s3.amazonaws.com/packages/appimage/zrythm-trial-1.0.0.alpha.18.2.1-x86_64.AppImage

unless I need to change the scripts for some reason, AppImage's will be available at the same link, just replace the version with the current release version. this is a trial version btw, the full version will be sold on the Zrythm website

I have only one issue with this AppImage on some systems:
```
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /tmp/.mount_zrythm4iZDPz/usr/share/zrythm/themes/icons/zrythm-dark/scalable/status/image-missing.svg: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

it seems to work for most people though

my build scripts are here: https://git.zrythm.org/zrythm/zrythm-installer/src/branch/master/appimage (I use appimage-builder and the author is aware of this issue but we don't know the cause)

**Comment by alex-tee** [comment]
note: I changed the link because AWS charges ridiculous fees for data transfer.. the trial builds can be directly fetched from our server:

https://www.zrythm.org/downloads/zrythm-trial-1.0.0.alpha.18.2.1-x86_64.AppImage

**Comment by coderofsalvation** [comment]
link is down again :/

idea: can somebody attach the appimage to the releases section of https://github.com/zrythm/zrythm/releases ?

**Comment by alex-tee** [comment]
@coderofsalvation 

There is no AppImage provided anymore. Quoting from [my post on our forums](https://forum.zrythm.org/t/zrythm-appimage-file):

> There is no AppImage provided anymore because the universal installer accomplishes the same thing with less middleware.

**Comment by probonopd** [comment]
Oh well. The point of AppImage is that you don't even need an installer...

**Comment by coderofsalvation** [comment]
true that, it's the most universal hasslefree way of running portable apps on any linux distro.
I guess it's more a bandwidth problem of creating/maintaining it, but from a marketing perspective it could be a good focus at some point.
